/*
 * Swiss Quiz — Fragen-/Antwort-Bestand, gruppiert nach Ort-ID.
 * Ein Ort hat mehr Fragen als pro Besuch gestellt werden; die App
 * zieht bei jedem Besuch zufällig eine Auswahl (siehe QUESTIONS_PER_STATION).
 *
 * Format je Frage: { q, options[], answer (Index der richtigen Option), topic, explain }
 * Die Reihenfolge der Optionen wird zur Laufzeit gemischt — answer bleibt
 * immer der Index in DIESER Liste.
 *
 * Neue Fragen einfach unter der passenden Ort-ID ergänzen.
 */

const QUESTIONS = {
  genf: [
    { q: "An welchem See liegt Genf?", options: ["Genfersee", "Bodensee", "Neuenburgersee", "Zürichsee"], answer: 0, topic: "Geografie",
      explain: "Der Genfersee (Lac Léman) ist der grösste See der Alpen und wird von der Schweiz und Frankreich geteilt." },
    { q: "Welche internationale Institution hat ihren europäischen Sitz in Genf?", options: ["UNO", "NATO", "EU-Kommission", "ASEAN"], answer: 0, topic: "Kultur",
      explain: "Genf beherbergt den europäischen UNO-Sitz (Palais des Nations) — und hier wurde 1863 das Rote Kreuz gegründet." },
    { q: "Welche Sprache spricht man in Genf?", options: ["Französisch", "Deutsch", "Italienisch", "Rätoromanisch"], answer: 0, topic: "Sprachen",
      explain: "Genf liegt in der Romandie, dem französischsprachigen Teil der Schweiz." },
    { q: "Wie heisst die grosse Wasserfontäne, das Wahrzeichen von Genf?", options: ["Jet d'Eau", "Wasserturm", "Staubbach", "Rheinfall"], answer: 0, topic: "Kurioses",
      explain: "Der Jet d'Eau schiesst rund 140 m in die Höhe und ist das Wahrzeichen der Stadt Genf." },
    { q: "Welche humanitäre Organisation wurde 1863 in Genf gegründet?", options: ["Rotes Kreuz", "Amnesty International", "Greenpeace", "WWF"], answer: 0, topic: "Geschichte",
      explain: "Henri Dunant gründete in Genf das Internationale Komitee vom Roten Kreuz — die Schweizer Flagge mit vertauschten Farben." },
    { q: "An welchem Ende des Genfersees liegt Genf?", options: ["am westlichen", "am östlichen", "am nördlichen", "am südlichen"], answer: 0, topic: "Geografie",
      explain: "Genf liegt am Südwestzipfel des Sees, dort wo die Rhône ihn wieder verlässt." },
  ],

  montreux: [
    { q: "Welches weltbekannte Musikfestival findet jährlich in Montreux statt?", options: ["Jazz Festival", "Opernfestspiele", "Fasnacht", "Techno-Parade"], answer: 0, topic: "Kultur",
      explain: "Das Montreux Jazz Festival zählt seit 1967 zu den bedeutendsten Musikfestivals der Welt." },
    { q: "Welches berühmte Wasserschloss liegt am Ufer bei Montreux?", options: ["Schloss Chillon", "Schloss Gruyères", "Schloss Thun", "Schloss Habsburg"], answer: 0, topic: "Geschichte",
      explain: "Das Château de Chillon liegt malerisch am Genfersee und ist das meistbesuchte historische Gebäude der Schweiz." },
    { q: "Welcher Rocksänger lebte in Montreux und hat dort ein Denkmal am See?", options: ["Freddie Mercury", "Elvis Presley", "Phil Collins", "Mick Jagger"], answer: 0, topic: "Kurioses",
      explain: "Queen-Sänger Freddie Mercury liebte Montreux; am Seeufer erinnert eine Bronzestatue an ihn." },
    { q: "An welchem See liegt Montreux?", options: ["Genfersee", "Neuenburgersee", "Bodensee", "Zugersee"], answer: 0, topic: "Geografie",
      explain: "Montreux liegt an der milden Riviera am Ostufer des Genfersees." },
    { q: "Welche legendäre Rockband besass in Montreux ein Tonstudio?", options: ["Queen", "ABBA", "The Beatles", "Nirvana"], answer: 0, topic: "Kultur",
      explain: "Queen kaufte die Mountain Studios; auf dem Album 'Made in Heaven' ist der Genfersee bei Montreux abgebildet." },
    { q: "In welcher Sprachregion liegt Montreux?", options: ["Romandie (französisch)", "Deutschschweiz", "Tessin (italienisch)", "Rätoromanisch"], answer: 0, topic: "Sprachen",
      explain: "Montreux liegt im französischsprachigen Kanton Waadt (Vaud)." },
  ],

  gruyeres: [
    { q: "Wofür ist das Städtchen Gruyères vor allem berühmt?", options: ["Hartkäse (Gruyère)", "Bier", "Salzminen", "Kohle"], answer: 0, topic: "Kultur",
      explain: "Der Gruyère ist einer der bekanntesten Schweizer Käse und Grundlage vieler Fondues." },
    { q: "Welches Schweizer Nationalgericht wird klassisch mit Gruyère zubereitet?", options: ["Käsefondue", "Rösti", "Birchermüesli", "Bratwurst"], answer: 0, topic: "Kurioses",
      explain: "Käsefondue besteht traditionell aus geschmolzenem Gruyère und Vacherin, mit Weisswein und Brot." },
    { q: "In welchem Kanton liegt Gruyères?", options: ["Freiburg", "Waadt", "Wallis", "Bern"], answer: 0, topic: "Geografie",
      explain: "Gruyères liegt im zweisprachigen Kanton Freiburg (Fribourg), genau an der deutsch-französischen Sprachgrenze." },
    { q: "Welcher Künstler, Schöpfer des Film-'Alien', hat in Gruyères ein Museum?", options: ["H.R. Giger", "Jean Tinguely", "Paul Klee", "Alberto Giacometti"], answer: 0, topic: "Kurioses",
      explain: "Der Oscar-prämierte H.R. Giger, Designer des 'Alien', zeigt in Gruyères sein düster-fantastisches Werk." },
    { q: "Welche Süssspeise mit Doppelrahm ist eine Freiburger Spezialität?", options: ["Meringues mit Doppelrahm", "Tiramisu", "Sachertorte", "Crème brûlée"], answer: 0, topic: "Kultur",
      explain: "Knusprige Meringues mit dem berühmten Gruyère-Doppelrahm (Crème double) sind eine regionale Spezialität." },
    { q: "In welcher Bergregion liegt Gruyères?", options: ["Freiburger Voralpen", "Engadin", "Tessiner Alpen", "Jura"], answer: 0, topic: "Geografie",
      explain: "Das Städtchen liegt in den Freiburger Voralpen, umgeben von Alpweiden — ideal für die Käseproduktion." },
  ],

  bern: [
    { q: "Welche Stadt ist der Regierungssitz (Bundesstadt) der Schweiz?", options: ["Bern", "Zürich", "Genf", "Luzern"], answer: 0, topic: "Politik",
      explain: "Offiziell hat die Schweiz keine 'Hauptstadt' — doch Regierung und Parlament sitzen seit 1848 in Bern." },
    { q: "Wie viele Mitglieder hat der Bundesrat, die Schweizer Regierung?", options: ["7", "5", "9", "26"], answer: 0, topic: "Politik",
      explain: "Der Bundesrat besteht aus 7 gleichberechtigten Mitgliedern; das Präsidium wechselt jährlich ('primus inter pares')." },
    { q: "Welches Tier ist das Wahrzeichen Berns und lebt im BärenPark?", options: ["Bär", "Steinbock", "Murmeltier", "Kuh"], answer: 0, topic: "Kurioses",
      explain: "Der Bär ziert das Berner Wappen — im BärenPark an der Aare leben echte Bären mitten in der Stadt." },
    { q: "Welcher berühmte Physiker entwickelte um 1905 in Bern seine Relativitätstheorie?", options: ["Albert Einstein", "Isaac Newton", "Nikola Tesla", "Galileo Galilei"], answer: 0, topic: "Kurioses",
      explain: "Einstein arbeitete am Berner Patentamt; sein 'Wunderjahr' 1905 machte ihn weltberühmt. Sein Wohnhaus ist heute ein Museum." },
    { q: "Welcher Fluss umfliesst die Berner Altstadt in einer markanten Schleife?", options: ["Aare", "Reuss", "Rhein", "Limmat"], answer: 0, topic: "Geografie",
      explain: "Die türkisgrüne Aare bildet die Schleife um die Altstadt — im Sommer eine beliebte, rasante Badestelle." },
    { q: "Was ist die mittelalterliche Berner Altstadt?", options: ["UNESCO-Welterbe", "eines der Sieben Weltwunder", "ein Nationalpark", "ein Freilichtmuseum"], answer: 0, topic: "Kultur",
      explain: "Die Altstadt mit ihren kilometerlangen Lauben (Arkaden) ist seit 1983 UNESCO-Welterbe." },
  ],

  interlaken: [
    { q: "Interlaken liegt zwischen zwei Seen — zwischen welchen?", options: ["Thuner- und Brienzersee", "Zuger- und Ägerisee", "Walen- und Zürichsee", "Bieler- und Neuenburgersee"], answer: 0, topic: "Geografie",
      explain: "'Interlaken' heisst 'zwischen den Seen' — der Ort liegt zwischen Thuner- und Brienzersee." },
    { q: "Das Jungfraujoch, die höchste Bahnstation Europas, trägt welchen Beinamen?", options: ["Top of Europe", "Dach der Welt", "Balkon der Alpen", "Tor zum Süden"], answer: 0, topic: "Kurioses",
      explain: "Auf 3454 m liegt die höchstgelegene Bahnstation Europas — das 'Top of Europe' am Jungfraujoch." },
    { q: "Welches berühmte Bergdreigestirn prägt die Region?", options: ["Eiger, Mönch & Jungfrau", "Matterhorn, Dom & Weisshorn", "Rigi, Pilatus & Titlis", "Säntis, Tödi & Piz Palü"], answer: 0, topic: "Geografie",
      explain: "Eiger, Mönch und Jungfrau bilden die berühmte Kulisse — die Eiger-Nordwand ist eine Legende des Alpinismus." },
    { q: "Wie hoch liegt das Jungfraujoch ungefähr?", options: ["3454 m", "2000 m", "4634 m", "1800 m"], answer: 0, topic: "Geografie",
      explain: "Die Station liegt auf 3454 m; die Jungfraubahn führt hinauf durch einen Tunnel mitten im Eiger und Mönch." },
    { q: "Welche Extremsportart machte das nahe Lauterbrunnental weltberühmt?", options: ["Base-Jumping / Wingsuit", "Surfen", "Formel 1", "Golf"], answer: 0, topic: "Kurioses",
      explain: "Die senkrechten Felswände des Lauterbrunnentals ziehen Base-Jumper und Wingsuit-Flieger aus aller Welt an." },
    { q: "In welchem Kanton liegt Interlaken?", options: ["Bern", "Wallis", "Uri", "Graubünden"], answer: 0, topic: "Geografie",
      explain: "Interlaken gehört zum Kanton Bern und gilt als Tor zum Berner Oberland." },
  ],

  zermatt: [
    { q: "Welcher berühmte Berg erhebt sich über Zermatt?", options: ["Matterhorn", "Eiger", "Mont Blanc", "Säntis"], answer: 0, topic: "Geografie",
      explain: "Das Matterhorn (4478 m) ist dank seiner Pyramidenform eines der meistfotografierten Bergmotive der Welt." },
    { q: "Wie heisst der höchste Gipfel der Schweiz?", options: ["Dufourspitze", "Matterhorn", "Jungfrau", "Piz Bernina"], answer: 0, topic: "Geografie",
      explain: "Die Dufourspitze im Monte-Rosa-Massiv misst 4634 m — höher als das berühmtere Matterhorn." },
    { q: "Was ist in Zermatt verboten?", options: ["Autos mit Verbrennungsmotor", "Fahrräder", "Kutschen", "Elektroautos"], answer: 0, topic: "Kurioses",
      explain: "Zermatt ist autofrei — es verkehren nur Elektrofahrzeuge und Pferdekutschen, um die klare Bergluft zu schützen." },
    { q: "In welchem Kanton liegt Zermatt?", options: ["Wallis", "Bern", "Tessin", "Uri"], answer: 0, topic: "Geografie",
      explain: "Zermatt liegt im Kanton Wallis, der die meisten Viertausender der Alpen beherbergt." },
    { q: "Wie erreicht man das autofreie Zermatt?", options: ["mit der Bahn", "über die Autobahn", "mit dem Schiff", "nur zu Fuss"], answer: 0, topic: "Alltag",
      explain: "Besucher parken in Täsch und fahren mit der Zahnradbahn die letzten Kilometer hinauf nach Zermatt." },
    { q: "Welche Zahnradbahn bringt Gäste zum Aussichtsberg Gornergrat?", options: ["Gornergratbahn", "Standseilbahn", "U-Bahn", "Pilatusbahn"], answer: 0, topic: "Kurioses",
      explain: "Die Gornergratbahn fährt seit 1898 auf 3089 m — mit einem der schönsten Blicke aufs Matterhorn." },
  ],

  locarno: [
    { q: "Wofür ist Locarno international bekannt?", options: ["Filmfestival", "Jazzfestival", "Autosalon", "Uhrenmesse"], answer: 0, topic: "Kultur",
      explain: "Beim Locarno Film Festival läuft das Kino auf der Piazza Grande unter freiem Himmel." },
    { q: "An welchem See liegt Locarno?", options: ["Lago Maggiore", "Luganersee", "Comer See", "Genfersee"], answer: 0, topic: "Geografie",
      explain: "Locarno liegt am Lago Maggiore — hier befindet sich mit rund 193 m der tiefste Punkt der Schweiz." },
    { q: "Wie hoch liegt der tiefste Punkt der Schweiz ungefähr?", options: ["193 m", "500 m", "800 m", "47 m"], answer: 0, topic: "Geografie",
      explain: "Rund 193 m über Meer am Lago Maggiore — während der höchste Punkt, die Dufourspitze, auf 4634 m liegt." },
    { q: "Wie heisst der Hauptpreis des Locarno Film Festivals?", options: ["Pardo d'oro (Goldener Leopard)", "Goldener Bär", "Goldene Palme", "Löwe von Venedig"], answer: 0, topic: "Kultur",
      explain: "Der 'Goldene Leopard' ist die höchste Auszeichnung — passend zum Wappentier des Festivals." },
    { q: "Welche Sprache spricht man in Locarno?", options: ["Italienisch", "Französisch", "Deutsch", "Rätoromanisch"], answer: 0, topic: "Sprachen",
      explain: "Locarno liegt im Tessin, dem italienischsprachigen Kanton der Schweiz." },
    { q: "Wofür sorgt das milde Klima am Lago Maggiore?", options: ["Palmen und Kamelien", "Gletscher", "Wüstensand", "Permafrost"], answer: 0, topic: "Kurioses",
      explain: "Dank mediterranem Klima gedeihen hier Palmen, Kamelien und sogar Zitrusfrüchte." },
  ],

  lugano: [
    { q: "Welche Sprache wird im Tessin gesprochen?", options: ["Italienisch", "Französisch", "Rätoromanisch", "Deutsch"], answer: 0, topic: "Sprachen",
      explain: "Das Tessin (Ticino) ist der italienischsprachige Kanton — mit mediterranem Klima und südlichem Lebensgefühl." },
    { q: "Wie viele offizielle Landessprachen hat die Schweiz?", options: ["4", "2", "3", "5"], answer: 0, topic: "Sprachen",
      explain: "Deutsch, Französisch, Italienisch und Rätoromanisch — vier Sprachen in einem kleinen Land." },
    { q: "Welcher See liegt bei Lugano?", options: ["Luganersee", "Lago Maggiore", "Genfersee", "Bodensee"], answer: 0, topic: "Geografie",
      explain: "Der Luganersee (Lago di Lugano) wird mit Italien geteilt — der Lago Maggiore liegt gleich nebenan bei Locarno." },
    { q: "In welchem Kanton liegt Lugano?", options: ["Tessin", "Graubünden", "Wallis", "Uri"], answer: 0, topic: "Geografie",
      explain: "Lugano ist die grösste Stadt des Kantons Tessin." },
    { q: "Wofür ist Lugano als Wirtschaftsstandort bekannt?", options: ["Finanzplatz", "Schwerindustrie", "Bergbau", "Fischerei"], answer: 0, topic: "Alltag",
      explain: "Lugano ist nach Zürich und Genf einer der wichtigsten Finanzplätze der Schweiz." },
    { q: "Welches Nachbarland umgibt die Region Lugano fast vollständig?", options: ["Italien", "Frankreich", "Österreich", "Deutschland"], answer: 0, topic: "Kultur",
      explain: "Das Tessin ist fast rundum von Italien umgeben — Mailand ist nur knapp eine Stunde entfernt." },
  ],

  chur: [
    { q: "Chur gilt als die … Stadt der Schweiz.", options: ["älteste", "grösste", "höchste", "jüngste"], answer: 0, topic: "Geschichte",
      explain: "Chur ist mit rund 5000 Jahren durchgehender Besiedlung die älteste Stadt der Schweiz." },
    { q: "Chur ist die Hauptstadt welches Kantons?", options: ["Graubünden", "St. Gallen", "Glarus", "Uri"], answer: 0, topic: "Geografie",
      explain: "Chur ist der Hauptort von Graubünden — dem grössten und einzigen dreisprachigen Kanton." },
    { q: "Welche berühmte Bahn ab Chur gehört zum UNESCO-Welterbe?", options: ["Rhätische Bahn", "Gotthardbahn", "Jungfraubahn", "Pilatusbahn"], answer: 0, topic: "Kurioses",
      explain: "Die Albula- und Berninalinie der Rhätischen Bahn ist UNESCO-Welterbe — hier fährt auch der Glacier Express." },
    { q: "Wie viele Amtssprachen hat der Kanton Graubünden?", options: ["drei", "zwei", "eine", "vier"], answer: 0, topic: "Sprachen",
      explain: "Deutsch, Rätoromanisch und Italienisch sind in Graubünden alle drei Amtssprachen — einmalig in der Schweiz." },
    { q: "An welchem grossen Fluss liegt Chur?", options: ["Rhein (Alpenrhein)", "Rhône", "Inn", "Aare"], answer: 0, topic: "Geografie",
      explain: "Chur liegt im Rheintal am jungen Alpenrhein, der später bei Basel die Schweiz verlässt." },
    { q: "Welcher Panoramazug verbindet über Chur Zermatt und St. Moritz?", options: ["Glacier Express", "Bernina Express", "GoldenPass", "Gotthard Panorama Express"], answer: 0, topic: "Kurioses",
      explain: "Der Glacier Express, der 'langsamste Schnellzug der Welt', fährt über Chur zwischen Zermatt und St. Moritz." },
  ],

  stmoritz: [
    { q: "Welche vierte Landessprache wird vor allem in Graubünden gesprochen?", options: ["Rätoromanisch", "Ladinisch", "Jenisch", "Schwyzerdütsch"], answer: 0, topic: "Sprachen",
      explain: "Rätoromanisch sprechen nur rund 0,5 % der Bevölkerung — fast alle davon in Graubünden." },
    { q: "Welcher ist der flächenmässig grösste Kanton der Schweiz?", options: ["Graubünden", "Bern", "Wallis", "Zürich"], answer: 0, topic: "Geografie",
      explain: "Graubünden ist der grösste Kanton — ein weites Bergland mit über 150 Tälern." },
    { q: "Wofür ist St. Moritz weltberühmt?", options: ["Wintersport & Olympia", "Schokolade", "Käse", "Uhren"], answer: 0, topic: "Kurioses",
      explain: "St. Moritz war zweimal Gastgeber der Olympischen Winterspiele (1928 und 1948) und gilt als Wiege des alpinen Wintertourismus." },
    { q: "Welche Art von Tourismus soll in St. Moritz erfunden worden sein?", options: ["Wintertourismus", "Städtetourismus", "Wandertourismus", "Badetourismus"], answer: 0, topic: "Kurioses",
      explain: "1864 wettete ein Hotelier mit Gästen, dass auch der Winter hier schön sei — der Beginn des alpinen Wintertourismus." },
    { q: "In welchem Tal liegt St. Moritz?", options: ["Engadin", "Lauterbrunnental", "Rheintal", "Mattertal"], answer: 0, topic: "Geografie",
      explain: "St. Moritz liegt im Oberengadin, einem hochgelegenen Seental in Graubünden." },
    { q: "Welches Spektakel findet im Winter auf dem zugefrorenen See von St. Moritz statt?", options: ["Pferderennen (White Turf)", "Formel 1", "Segelregatta", "Ruderrennen"], answer: 0, topic: "Kurioses",
      explain: "Auf dem gefrorenen See finden Pferderennen ('White Turf') und sogar Polo auf Schnee statt." },
  ],

  stgallen: [
    { q: "Wofür ist St. Gallen als UNESCO-Welterbe bekannt?", options: ["Stiftsbibliothek", "Fussballstadion", "Salzmine", "Weinkeller"], answer: 0, topic: "Kultur",
      explain: "Die barocke Stiftsbibliothek St. Gallen ist eine der ältesten und prachtvollsten Bibliotheken der Welt." },
    { q: "Wofür war St. Gallen im 19. Jahrhundert weltberühmt?", options: ["Stickerei", "Uhren", "Käse", "Schokolade"], answer: 0, topic: "Kurioses",
      explain: "Die St. Galler Stickerei war weltweit gefragt — bis heute liefert die Stadt feine Stoffe an die Haute Couture." },
    { q: "In welcher Region der Schweiz liegt St. Gallen?", options: ["Ostschweiz", "Westschweiz", "Tessin", "Wallis"], answer: 0, topic: "Geografie",
      explain: "St. Gallen ist das Zentrum der Ostschweiz, nahe dem Bodensee und dem Fürstentum Liechtenstein." },
    { q: "In der Nähe welches grossen Gewässers liegt St. Gallen?", options: ["Bodensee", "Genfersee", "Lago Maggiore", "Vierwaldstättersee"], answer: 0, topic: "Geografie",
      explain: "St. Gallen liegt nahe dem Bodensee, den sich die Schweiz mit Deutschland und Österreich teilt." },
    { q: "Wer gründete der Legende nach die Stadt St. Gallen?", options: ["der Mönch Gallus", "Julius Cäsar", "Wilhelm Tell", "Napoleon"], answer: 0, topic: "Geschichte",
      explain: "Der irische Wandermönch Gallus liess sich um 612 hier als Einsiedler nieder — daraus wuchsen Kloster und Stadt." },
    { q: "Wie heisst der auffällige, knallrot belegte öffentliche Raum in St. Gallen?", options: ["Roter Platz (Stadtlounge)", "Grüner Ring", "Blaues Band", "Weisser Hof"], answer: 0, topic: "Kurioses",
      explain: "Die 'Stadtlounge' ist ein rotes 'Wohnzimmer' mitten in der Stadt — mit Sofas und Autos auf rotem Belag." },
  ],

  appenzell: [
    { q: "In Appenzell wird per Handaufheben auf dem Platz abgestimmt. Wie heisst das?", options: ["Landsgemeinde", "Referendum", "Ständerat", "Vernehmlassung"], answer: 0, topic: "Politik",
      explain: "Die Landsgemeinde ist eine der ältesten Formen direkter Demokratie — offene Abstimmung per Handerheben unter freiem Himmel." },
    { q: "Appenzell Innerrhoden führte als letzter Kanton das Frauenstimmrecht ein — wann?", options: ["1990", "1971", "1959", "2004"], answer: 0, topic: "Geschichte",
      explain: "Erst 1990 mussten die Innerrhoder Männer per Bundesgericht das kantonale Frauenstimmrecht zulassen — 19 Jahre nach dem nationalen." },
    { q: "Wofür ist die Region Appenzell bekannt?", options: ["Brauchtum & Alpaufzug", "Autoindustrie", "Hochhäuser", "Seehäfen"], answer: 0, topic: "Kultur",
      explain: "Appenzell pflegt lebendiges Brauchtum: farbige Trachten, Streichmusik und den feierlichen Alpaufzug im Frühling." },
    { q: "Wofür ist der Appenzeller Käse bekannt?", options: ["würzige Kräutersulz", "grosse Löcher", "Blauschimmel", "Rauchgeschmack"], answer: 0, topic: "Kurioses",
      explain: "Appenzeller wird während der Reifung mit einer geheimen Kräutersulz eingerieben — daher sein kräftiges Aroma." },
    { q: "Welcher Berg ist der Hausberg des Appenzellerlandes?", options: ["Säntis", "Matterhorn", "Pilatus", "Titlis"], answer: 0, topic: "Geografie",
      explain: "Der Säntis (2502 m) im Alpstein bietet bei klarer Sicht Blick auf sechs Länder." },
    { q: "In wie viele Halbkantone ist Appenzell geteilt?", options: ["zwei (Inner- und Ausserrhoden)", "drei", "vier", "gar keine"], answer: 0, topic: "Politik",
      explain: "Seit der Reformation 1597 ist Appenzell geteilt: Innerrhoden (katholisch) und Ausserrhoden (reformiert)." },
  ],

  zuerich: [
    { q: "Wofür sind die Schweizer Bahnen (SBB) besonders bekannt?", options: ["Pünktlichkeit", "Gratis-Tickets", "Nachtzüge", "Doppeldecker"], answer: 0, topic: "Alltag",
      explain: "Pünktlichkeit gilt als Schweizer Tugend — das dichte Bahnnetz bringt fast jedes Dorf zuverlässig ans Netz." },
    { q: "Welche Währung gilt in der Schweiz?", options: ["Schweizer Franken", "Euro", "Schilling", "Krone"], answer: 0, topic: "Alltag",
      explain: "Die Schweiz gehört nicht zur Eurozone; bezahlt wird mit dem Schweizer Franken (CHF)." },
    { q: "Welches Schweizer Produkt trägt das Matterhorn im Logo?", options: ["Toblerone", "Lindt-Kugel", "Ovomaltine", "Rivella"], answer: 0, topic: "Kurioses",
      explain: "Die dreieckige Toblerone zeigt das Matterhorn — mit einem versteckten Bären im Bild, dem Wappentier von Bern." },
    { q: "An welchem Fluss und See liegt Zürich?", options: ["Limmat und Zürichsee", "Aare und Thunersee", "Reuss und Vierwaldstättersee", "Rhein und Bodensee"], answer: 0, topic: "Geografie",
      explain: "Die Limmat fliesst aus dem Zürichsee mitten durch die Stadt." },
    { q: "Wofür ist die Zürcher Bahnhofstrasse weltbekannt?", options: ["Luxus-Einkaufsmeile", "längste Rolltreppe", "ältester Bahnhof", "grösster Wochenmarkt"], answer: 0, topic: "Kurioses",
      explain: "Die Bahnhofstrasse zählt zu den teuersten und exklusivsten Einkaufsstrassen der Welt." },
    { q: "Welche Kunstbewegung entstand 1916 im Cabaret Voltaire in Zürich?", options: ["Dadaismus", "Impressionismus", "Kubismus", "Bauhaus"], answer: 0, topic: "Kultur",
      explain: "Im Cabaret Voltaire gründeten Künstler mitten im Ersten Weltkrieg die Dada-Bewegung." },
  ],

  luzern: [
    { q: "Welches Jahr gilt als Gründungsjahr der Eidgenossenschaft?", options: ["1291", "1848", "1515", "1648"], answer: 0, topic: "Geschichte",
      explain: "1291 schlossen Uri, Schwyz und Unterwalden den Bund — am Rütli, einer Wiese am Vierwaldstättersee." },
    { q: "An welchem See liegt Luzern?", options: ["Vierwaldstättersee", "Zugersee", "Thunersee", "Walensee"], answer: 0, topic: "Geografie",
      explain: "Der Vierwaldstättersee ist von Bergen wie Pilatus und Rigi umgeben und eng mit der Tell-Sage verbunden." },
    { q: "Welcher Freiheitsheld soll mit der Armbrust einen Apfel getroffen haben?", options: ["Wilhelm Tell", "Winkelried", "Henri Dunant", "Niklaus von Flüe"], answer: 0, topic: "Geschichte",
      explain: "Wilhelm Tell ist die legendäre Symbolfigur des Freiheitswillens — verewigt in Schillers Drama, verortet in der Innerschweiz." },
    { q: "Welche berühmte überdachte Holzbrücke steht in Luzern?", options: ["Kapellbrücke", "Rialtobrücke", "Teufelsbrücke", "Ponte Vecchio"], answer: 0, topic: "Kultur",
      explain: "Die Kapellbrücke aus dem 14. Jh. mit dem markanten Wasserturm ist eine der ältesten Holzbrücken Europas." },
    { q: "Welches Denkmal, ein sterbender Löwe, erinnert in Luzern an gefallene Schweizergardisten?", options: ["Löwendenkmal", "Bundesbrief", "Rütli-Stein", "Tell-Statue"], answer: 0, topic: "Kultur",
      explain: "Das in Fels gehauene Löwendenkmal nannte Mark Twain 'das traurigste und ergreifendste Stück Stein der Welt'." },
    { q: "Welcher Hausberg mit steilster Zahnradbahn der Welt liegt bei Luzern?", options: ["Pilatus", "Säntis", "Matterhorn", "Jungfrau"], answer: 0, topic: "Geografie",
      explain: "Auf den Pilatus führt die steilste Zahnradbahn der Welt; auch die Rigi, die 'Königin der Berge', liegt hier." },
  ],

  schaffhausen: [
    { q: "Bei Schaffhausen liegt der grösste Wasserfall Europas. Wie heisst er?", options: ["Rheinfall", "Trümmelbachfälle", "Staubbachfall", "Reichenbachfall"], answer: 0, topic: "Geografie",
      explain: "Der Rheinfall ist mit 23 m Höhe und gewaltiger Wassermenge der grösste Wasserfall Europas." },
    { q: "Schaffhausen ist der einzige Kanton, der grösstenteils … des Rheins liegt.", options: ["nördlich", "südlich", "östlich", "westlich"], answer: 0, topic: "Geografie",
      explain: "Schaffhausen liegt als einziger Kanton fast vollständig nördlich des Rheins, fast rundum von Deutschland umgeben." },
    { q: "Welche Festung thront über der Altstadt von Schaffhausen?", options: ["Munot", "Chillon", "Aarburg", "Habsburg"], answer: 0, topic: "Kurioses",
      explain: "Der Munot ist eine ringförmige Festung aus dem 16. Jahrhundert — das Wahrzeichen von Schaffhausen." },
    { q: "Welches Nachbarland umgibt den Kanton Schaffhausen fast vollständig?", options: ["Deutschland", "Frankreich", "Österreich", "Italien"], answer: 0, topic: "Geografie",
      explain: "Schaffhausen ragt als nördlichster Kanton weit nach Deutschland hinein." },
    { q: "Wie kann man den Rheinfall aus nächster Nähe erleben?", options: ["mit dem Boot zum Felsen", "per Seilbahn", "im U-Boot", "nur aus der Ferne"], answer: 0, topic: "Kurioses",
      explain: "Boote bringen Besucher bis zum Felsen mitten im Rheinfall, den man über eine Treppe erklimmen kann." },
    { q: "In welchem Jahrhundert wurde die Festung Munot erbaut?", options: ["im 16. Jh.", "im 12. Jh.", "im 19. Jh.", "im 20. Jh."], answer: 0, topic: "Geschichte",
      explain: "Die ringförmige Festung Munot entstand im 16. Jahrhundert nach den Befestigungsideen aus Dürers Lehrbuch." },
  ],

  basel: [
    { q: "Wie heisst das grosse Basler Fest, das mit dem 'Morgenstreich' um 4 Uhr früh beginnt?", options: ["Fasnacht", "Sechseläuten", "Escalade", "Älplerfest"], answer: 0, topic: "Kultur",
      explain: "Die Basler Fasnacht ist die grösste der Schweiz und UNESCO-Kulturerbe — sie startet im Dunkeln mit dem Morgenstreich." },
    { q: "Ist die Schweiz Mitglied der Europäischen Union (EU)?", options: ["Nein", "Ja", "Nur assoziiert", "Seit 2002"], answer: 0, topic: "Politik",
      explain: "Die Schweiz ist kein EU-Mitglied; sie regelt ihre Beziehungen über bilaterale Verträge. 2002 trat sie aber der UNO bei." },
    { q: "Wann erhielten Frauen das Stimmrecht auf nationaler Ebene?", options: ["1971", "1918", "1948", "1991"], answer: 0, topic: "Geschichte",
      explain: "Erst 1971 durften Frauen national abstimmen — im Kanton Appenzell Innerrhoden sogar erst 1990, per Gerichtsentscheid." },
    { q: "An welchem Fluss liegt Basel?", options: ["Rhein", "Rhône", "Aare", "Limmat"], answer: 0, topic: "Geografie",
      explain: "Basel liegt am 'Rheinknie', wo der Rhein von der West- in die Nordrichtung dreht — mit dem einzigen Rheinhafen der Schweiz." },
    { q: "Wofür ist Basel als Kulturstadt bekannt?", options: ["höchste Museumsdichte", "grösstes Casino", "grösstes Skigebiet", "meiste Weinberge"], answer: 0, topic: "Kultur",
      explain: "Basel hat die höchste Museumsdichte der Schweiz; das Kunstmuseum ist eines der ältesten öffentlichen der Welt." },
    { q: "Basel bildet ein 'Dreiländereck' mit welchen zwei Nachbarländern?", options: ["Deutschland und Frankreich", "Italien und Österreich", "Österreich und Liechtenstein", "Frankreich und Italien"], answer: 0, topic: "Kurioses",
      explain: "Am Dreiländereck am Rhein treffen die Schweiz, Deutschland und Frankreich aufeinander." },
  ],

  neuchatel: [
    { q: "Wofür ist die Region Neuenburg / der Jura weltberühmt?", options: ["Uhrmacherei", "Schokolade", "Bergbau", "Fischerei"], answer: 0, topic: "Kurioses",
      explain: "Im Jurabogen — etwa in La Chaux-de-Fonds — schlägt das Herz der Schweizer Uhrmacherei." },
    { q: "Die Uhrmacherstadt La Chaux-de-Fonds im Kanton Neuenburg ist …", options: ["UNESCO-Welterbe", "ein Nationalpark", "ein Skigebiet", "ein Weltwunder"], answer: 0, topic: "Kultur",
      explain: "Ihr schachbrettartiger Stadtplan, ganz auf die Uhrenindustrie ausgerichtet, machte La Chaux-de-Fonds zum UNESCO-Welterbe." },
    { q: "Welche Sprache spricht man in Neuenburg?", options: ["Französisch", "Deutsch", "Italienisch", "Rätoromanisch"], answer: 0, topic: "Sprachen",
      explain: "Neuenburg (Neuchâtel) liegt in der Romandie, der französischsprachigen Westschweiz." },
    { q: "An welchem See liegt Neuenburg?", options: ["Neuenburgersee", "Genfersee", "Bodensee", "Zürichsee"], answer: 0, topic: "Geografie",
      explain: "Der Neuenburgersee ist der grösste See, der vollständig in der Schweiz liegt." },
    { q: "Welches Kräuterdestillat wurde im Neuenburger Val-de-Travers erfunden?", options: ["Absinth", "Kirsch", "Grappa", "Williams"], answer: 0, topic: "Kurioses",
      explain: "Im Val-de-Travers entstand der Absinth, die 'grüne Fee' — lange verboten, heute wieder legal." },
    { q: "Welcher berühmte Architekt der Moderne wurde in La Chaux-de-Fonds geboren?", options: ["Le Corbusier", "Mario Botta", "Gustave Eiffel", "Antoni Gaudí"], answer: 0, topic: "Kultur",
      explain: "Le Corbusier, einer der einflussreichsten Architekten des 20. Jahrhunderts, stammt aus La Chaux-de-Fonds." },
  ],

  aletsch: [
    { q: "Was ist der Grosse Aletschgletscher?", options: ["der grösste Gletscher der Alpen", "der höchste Berg", "der längste Fluss", "der tiefste See"], answer: 0, topic: "Geografie",
      explain: "Der Aletschgletscher ist mit rund 20 km Länge der grösste und längste Gletscher der Alpen." },
    { q: "Wozu gehört die Region Jungfrau-Aletsch?", options: ["UNESCO-Welterbe", "Nationalpark Engadin", "Siebengestirn", "Weltwunder der Antike"], answer: 0, topic: "Kultur",
      explain: "Jungfrau-Aletsch war 2001 das erste Naturobjekt der Alpen auf der UNESCO-Welterbeliste." },
    { q: "In welchem Kanton liegt der Aletschgletscher?", options: ["Wallis", "Bern", "Uri", "Graubünden"], answer: 0, topic: "Geografie",
      explain: "Der Aletschgletscher liegt im Kanton Wallis, gespeist vom Schnee rund um die Jungfrau." },
    { q: "Was geschieht mit dem Aletschgletscher wie mit fast allen Alpengletschern?", options: ["er schmilzt und zieht sich zurück", "er wächst stetig", "er bleibt unverändert", "er wird zu Fels"], answer: 0, topic: "Kurioses",
      explain: "Der Klimawandel lässt den Aletschgletscher jährlich schmelzen — er verliert deutlich an Länge und Dicke." },
    { q: "Wie lang ist der Grosse Aletschgletscher ungefähr?", options: ["rund 20 km", "rund 200 km", "rund 2 km", "rund 60 km"], answer: 0, topic: "Geografie",
      explain: "Rund 20 km Eisstrom — er speichert gewaltige Mengen Süsswasser mitten in den Alpen." },
    { q: "Wie erreicht man die Aussichtspunkte am Aletsch am besten?", options: ["mit Seilbahnen (z. B. Eggishorn)", "mit dem Schiff", "über die Autobahn", "mit dem Flugzeug"], answer: 0, topic: "Alltag",
      explain: "Seilbahnen bringen Besucher auf Aussichtsberge wie das Eggishorn mit Blick auf den mächtigen Eisstrom." },
  ],

  gotthard: [
    { q: "Was ist der Gotthard-Basistunnel?", options: ["der längste Eisenbahntunnel der Welt", "die höchste Brücke Europas", "der tiefste See der Alpen", "die längste Seilbahn"], answer: 0, topic: "Kurioses",
      explain: "Mit 57 km ist der Gotthard-Basistunnel der längste Eisenbahntunnel der Welt — er unterquert die Alpen fast eben." },
    { q: "Welche Bedeutung hat der Gotthard für die Schweiz?", options: ["zentrale Nord-Süd-Verbindung", "Landesgrenze", "höchster Berg", "grösster See"], answer: 0, topic: "Geografie",
      explain: "Der Gotthard ist seit Jahrhunderten die wichtigste Alpenquerung zwischen Nord- und Südeuropa." },
    { q: "Welcher grosse Fluss entspringt am Gotthardmassiv?", options: ["Reuss", "Limmat", "Birs", "Thur"], answer: 0, topic: "Geografie",
      explain: "Rund ums Gotthardmassiv entspringen Reuss, Rhône, Rhein und Ticino — ein wahres 'Wasserschloss' Europas." },
    { q: "Wie heisst die sagenumwobene Brücke in der Schöllenenschlucht am Gotthard?", options: ["Teufelsbrücke", "Kapellbrücke", "Rheinbrücke", "Ponte dei Salti"], answer: 0, topic: "Kurioses",
      explain: "Der Sage nach half der Teufel beim Bau der Teufelsbrücke — als Lohn wollte er die Seele des ersten Passanten." },
    { q: "Welche Grenze bildet der Gotthard mitten in der Schweiz?", options: ["Sprach- und Klimagrenze", "Zeitzonengrenze", "Währungsgrenze", "Landesgrenze"], answer: 0, topic: "Geografie",
      explain: "Nördlich Deutsch und Alpenklima, südlich Italienisch und mildes Tessin — der Gotthard trennt zwei Welten." },
    { q: "Wie führt heute der schnellste Weg unter dem Gotthard hindurch?", options: ["durch den Basistunnel (Bahn)", "über die Passstrasse", "mit der Seilbahn", "per Fähre"], answer: 0, topic: "Alltag",
      explain: "Seit 2016 fahren Züge in gut 20 Minuten durch den flachen Basistunnel statt mühsam über die hohe Passhöhe." },
  ],

  solothurn: [
    { q: "Als was gilt Solothurn?", options: ["schönste Barockstadt der Schweiz", "grösste Stadt der Schweiz", "höchstgelegene Stadt", "älteste Stadt"], answer: 0, topic: "Kultur",
      explain: "Solothurn gilt als die schönste Barockstadt der Schweiz — ein Ensemble aus Kirchen, Toren und Brunnen." },
    { q: "Welche Zahl spielt in Solothurn eine ganz besondere Rolle?", options: ["die 11", "die 7", "die 3", "die 100"], answer: 0, topic: "Kurioses",
      explain: "Solothurn hat 11 Kirchen und Kapellen, 11 Brunnen und 11 Türme; die St.-Ursen-Kathedrale hat 11 Altäre und 11 Glocken." },
    { q: "An welchem Fluss liegt Solothurn?", options: ["Aare", "Rhein", "Reuss", "Limmat"], answer: 0, topic: "Geografie",
      explain: "Solothurn liegt an der Aare, am Fuss des Juras mit dem Hausberg Weissenstein." },
    { q: "Solothurn war über 200 Jahre Sitz der Gesandten welches Landes?", options: ["Frankreich", "Spanien", "England", "Russland"], answer: 0, topic: "Geschichte",
      explain: "Die französischen Botschafter residierten in Solothurn — daher der noble, grosszügige Barockstil der Stadt." },
    { q: "Welche Sprache spricht man in Solothurn?", options: ["Deutsch", "Französisch", "Italienisch", "Rätoromanisch"], answer: 0, topic: "Sprachen",
      explain: "Solothurn liegt in der Deutschschweiz, nahe der Sprachgrenze zur französischsprachigen Romandie." },
    { q: "Welcher Jura-Hausberg mit Alpenpanorama liegt bei Solothurn?", options: ["Weissenstein", "Säntis", "Pilatus", "Rigi"], answer: 0, topic: "Geografie",
      explain: "Der Weissenstein bietet einen weiten Panoramablick über das Mittelland bis zur ganzen Alpenkette." },
  ],
};
